version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pideya_extraor
    ports:
      - "5125:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@ssword1
      POSTGRES_DB: pideya
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
